import { Post } from "./type/post.type";

export const PostExample: Post[] = [
    {
        id: "wrtyjkdrtyhjnbvcx",
        subreddit: "r/dunno",
        subredditid: "jghbvncsoeifh",
        user: "r/surprised-apple",
        content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Sed consectetur sem in odio; justo tortor. Fermentum nunc mattis finibus integer pellentesque id. Curae augue erat ipsum proin potenti. Integer at porttitor quisque lectus sit curabitur cursus. Mattis sapien varius senectus consectetur enim pellentesque. Dis aptent sodales montes donec placerat auctor nibh class.Sem fermentum praesent molestie dignissim mus. Posuere vel mus per finibus pellentesque tortor pharetra. Fringilla facilisis malesuada urna euismod dictum malesuada. Adipiscing ligula enim ac convallis aenean commodo sapien. Efficitur fringilla ut pulvinar pretium eget elementum sed consectetur. Nullam ultricies mi turpis urna ligula bibendum. Blandit pellentesque massa class condimentum quis, hac quis ex.Sagittis felis cursus congue velit donec. Pretium ex cras sodales ipsum vivamus et rhoncus ultrices et. Eget mauris quisque; lorem penatibus dolor in vehicula pretium? Sollicitudin condimentum orci non nam; fermentum sem risus. Massa vehicula platea bibendum class phasellus; semper ac mauris. Ipsum dictum malesuada nam lobortis facilisi lacinia arcu dapibus. Amet aliquet aenean viverra himenaeos habitant ultrices dictumst maecenas consequat. Morbi rhoncus vivamus felis consequat donec condimentum et himenaeos? Donec etiam etiam ligula diam non nullam nisl id porttitor. Class convallis ultricies eros elementum libero. Non netus congue accumsan potenti vitae phasellus nunc. Lacinia euismod morbi inceptos cras; curabitur dui vestibulum tortor. Dis eros tempus dis litora pretium nullam ex morbi. Quisque finibus a mauris malesuada fusce torquent? Magnis senectus sollicitudin molestie curae velit natoque. Odio morbi tortor interdum litora facilisis. Pulvinar tristique tincidunt parturient lacinia feugiat lacinia nostra fringilla. Duis condimentum condimentum finibus justo morbi ullamcorper tincidunt duis ullamcorper. Molestie dis suspendisse venenatis integer; ridiculus nostra maximus. Metus varius viverra taciti hac at porttitor lacus lacinia integer. Bibendum sollicitudin venenatis purus auctor suspendisse pretium aenean a proin. Ligula vulputate etiam pulvinar ut curabitur at. Quis nulla massa varius volutpat rhoncus pretium adipiscing. Parturient sit maximus justo malesuada nisl aliquam eu. Varius nam natoque laoreet erat himenaeos laoreet turpis a magnis. Orci ultricies vel nostra ridiculus a sed natoque. Metus torquent pulvinar ultrices; quis non placerat.",
        title: "Lorem",
        upvotes: 1000,
        downvotes: 0,
        avatarPath: ""
    },
    {
        id: "mjuyewsdvbn",
        subreddit: "r/dunno",
        subredditid: "laowiueyrgf",
        user: "r/unamazed-egg",
        content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Sed consectetur sem in odio; justo tortor. Fermentum nunc mattis finibus integer pellentesque id. Curae augue erat ipsum proin potenti. Integer at porttitor quisque lectus sit curabitur cursus. Mattis sapien varius senectus consectetur enim pellentesque. Dis aptent sodales montes donec placerat auctor nibh class.Sem fermentum praesent molestie dignissim mus. Posuere vel mus per finibus pellentesque tortor pharetra. Fringilla facilisis malesuada urna euismod dictum malesuada. Adipiscing ligula enim ac convallis aenean commodo sapien. Efficitur fringilla ut pulvinar pretium eget elementum sed consectetur. Nullam ultricies mi turpis urna ligula bibendum. Blandit pellentesque massa class condimentum quis, hac quis ex.Sagittis felis cursus congue velit donec. Pretium ex cras sodales ipsum vivamus et rhoncus ultrices et. Eget mauris quisque; lorem penatibus dolor in vehicula pretium? Sollicitudin condimentum orci non nam; fermentum sem risus. Massa vehicula platea bibendum class phasellus; semper ac mauris. Ipsum dictum malesuada nam lobortis facilisi lacinia arcu dapibus. Amet aliquet aenean viverra himenaeos habitant ultrices dictumst maecenas consequat. Morbi rhoncus vivamus felis consequat donec condimentum et himenaeos? Donec etiam etiam ligula diam non nullam nisl id porttitor. Class convallis ultricies eros elementum libero. Non netus congue accumsan potenti vitae phasellus nunc. Lacinia euismod morbi inceptos cras; curabitur dui vestibulum tortor. Dis eros tempus dis litora pretium nullam ex morbi. Quisque finibus a mauris malesuada fusce torquent? Magnis senectus sollicitudin molestie curae velit natoque. Odio morbi tortor interdum litora facilisis. Pulvinar tristique tincidunt parturient lacinia feugiat lacinia nostra fringilla. Duis condimentum condimentum finibus justo morbi ullamcorper tincidunt duis ullamcorper. Molestie dis suspendisse venenatis integer; ridiculus nostra maximus. Metus varius viverra taciti hac at porttitor lacus lacinia integer. Bibendum sollicitudin venenatis purus auctor suspendisse pretium aenean a proin. Ligula vulputate etiam pulvinar ut curabitur at. Quis nulla massa varius volutpat rhoncus pretium adipiscing. Parturient sit maximus justo malesuada nisl aliquam eu. Varius nam natoque laoreet erat himenaeos laoreet turpis a magnis. Orci ultricies vel nostra ridiculus a sed natoque. Metus torquent pulvinar ultrices; quis non placerat.",
        title: "Lorem",
        upvotes: 1000,
        downvotes: 0,
        avatarPath: ""
    }
]